# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21540647ed56ca380feef08f9b597fadfa6fc43d2965d3d59b2ce1f97b94a540c23d7feef52b551aff45743bd9c78cc64b615f06dcf28eee77c6267fb591c983

test:
  secret_key_base: ab2aaed2f246aaca8d402ffd6e1c3bfa2fd42c10d3414d8ac830657fe9b7544949df6335354908b0f06edb4606817023b6bf674a07dc73f72fe7b190c5f50921

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
